# -*- Mode: python; indent-tabs-mode: nil; tab-width: 40 -*-
# This Source Code Form is subject to the terms of the Mozilla Public
# License, v. 2.0. If a copy of the MPL was not distributed with this
# file, You can obtain one at http://mozilla.org/MPL/2.0/.

Classes = [
    {
        'cid': '{c034724f-9057-4075-9e88-589f93a68c2c}',
        'contract_ids': ['@mozilla.org/network/protocol/about;1?what=nullpath-blocked'],
        'esModule': 'moz-src:///browser/components/nullpath/network/NullpathAboutBlocked.sys.mjs',
        'constructor': 'NullpathAboutBlocked',
    },
]
